### ISSUE TITLE
Do not display private packages on the Data Package Server

### ISSUE THREAD

**Issue by tkuester** [tkuester/taky#13]

**Comment by doug-fitzmaurice-rowden** [comment]
(Moving discussion from #4 as I think it applies more here)

The way ATAK does it is to PUT to the `/Marti/api/sync/metdata/<hash>/tool` endpoint, setting the package to private if it was sent directly to another contact, and to public if it was just sent to the server.

I think that behaviour still makes sense (and the endpoint is already there in taky), so the only thing you can't do is upload a package to the server that only you can see. Seems like kind of a niche case, but a config setting would be a neat solution for that.
