### ISSUE TITLE
Dp ssl

### ISSUE THREAD

**Issue by capitanxitry** [tkuester/taky#17]
Hi there!
Read your issue on ATAK client... and was curious about the feedback. How evasive:( literally the civtak is the miltak that has several features removed. One of them is the SSL protocol for the dp port of the tak-server. If you investigated the code of fts, for example, you discovered that it has the feature. But it is mented to be for the EUDs that support it. I might provide you with miltak version having you email. Bet it gonna be usefull

**Comment by Cloud-RF** [comment]
FYI ATAK is export controlled / EAR99. Please check before you send.
https://drive.google.com/file/d/1jELcvs5NmO6vPKZX7-jQgOqKEDfNGy4M/view
https://www.trade.gov/eccn-and-export-administration-regulation-ear99

**Comment by capitanxitry** [comment]
I will:)
