### ISSUE TITLE
Implement a TCP Monitoring Port

### ISSUE THREAD

**Issue by tkuester** [tkuester/taky#25]
Taky was originally written to be either SSL, or TCP -- but not both at the same time. However, it may be useful to allow adding a TCP port. Many administrators have scripts to monitor (or inject) COT data to the server, and adding client certificates is a lot of overhead.

It would be wonderful to allow the server admin to configure taky to serve SSL on 0.0.0.0, and listen for TCP on 127.0.0.1 (for example). Perhaps they could even specify further, that the TCP port is write only, or read only.

**Comment by XPav** [comment]
This would be a very useful feature!  iTAK only supports SSL, so with Taky, I'm currently forced to choose between "have simple custom app to inject CoT" or "support iPhones".
