### ISSUE TITLE
Investigate what is needed to get taky running on Windows

### ISSUE THREAD

**Issue by tkuester** [tkuester/taky#29]
I briefly checked to see if taky would run natively on Windows -- it does seem to run, but I have not had time to test. Windows is a "second class citizen" in my book, but I don't want to leave users out in the cold for no reason.

**Comment by doug-fitzmaurice-rowden** [comment]
The `taky` CoT command should be fine, but `taky_dps` won't work as Gunicorn doesn't work on windows:
https://github.com/benoitc/gunicorn/issues/524

Options are:
* Migrate to a different WSGI server (annoying)
* Suggest WSL2 on windows, either directly in the Linux shell or via Docker

I'd suggest the second - I've run taky both ways on my Windows machine and it works well. I'll work up a docs page.

**Comment by tkuester** [comment]
Just due to the additional support offered by docker / WSL, I think I'm going to close this issue for now. (Additionally, I don't really have a Windows machine to test on!)

The official stance is that if anyone discovers something that is low hanging fruit to make things easier to run, I'll bring it right in. But the primary target will be linux OS's.
