### ISSUE TITLE
Data package download fails (ATAK tries download from 0.0.0.0:8080)

### ISSUE THREAD

**Issue by sgofferj** [tkuester/taky#35]
I'm trying to send a datapackage via ssl from one EUD to another. CoT works fine. I can see the sending EUD upload the data package in the logs and the files appear on te server. However, the receiving device shows a count-up to 10 in the notifications and then complains that it failed to download the file from 0.0.0.0:8080. Is that a server-side problem or a client-side problem? Both EUDs are running ATAK 4.3.1. The server is taky-docker.

**Comment by sgofferj** [comment]
Upload DP to server through datapackage -> send and download that datapackage from another EUD works. Just the direct sending to a contact doesn't.

**Comment by sgofferj** [comment]
I have been trying to codesurf a little bit through the taky dps code with very limited Python skills and one thing doesn't make sense to me. Pretty much everywhere, the code uses `app_config.get("section", "param")` to get some config value. just in /taky/dps/views/datapackage.py -> url_for, it accesses some global object `app.config["param"]`.

**Comment by tkuester** [comment]
@sgofferj I think this issue is quite closely related, and I think I may know what's been going wrong here.

Can you check your config file (if it still exists!) and see if the `public_ip` is set to `0.0.0.0`?

**Comment by sgofferj** [comment]
@tkuester I set public_ip to the fqdn but bind_ip is 0.0.0.0.
I'm using @skadakar 's docker image nowadays and that hot patches the one line of code to make it work.

**Comment by tkuester** [comment]
Awesome. I have the feeling this bug will be resolved with 2aea869. Please feel free to take a look in the next branch!

**Comment by tkuester** [comment]
This issue was resolved in c774999 as well.
