### ISSUE TITLE
Use unique names for the certificates in the client data package

### ISSUE THREAD

**Issue by reldred** [tkuester/taky#39]
![image](https://user-images.githubusercontent.com/19522569/134772221-d254a7a4-3429-47cf-b02a-aab957b990db.png)
The following _highly descriptive_ error is produced in WinTAK when retrieving list of data packages or when attempting to upload a data package.

Configuration of TAKY server/firewalls/et all work correctly in ATAK.

**Comment by tkuester** [comment]
Thanks for the report. Even if this isn't an issue with taky and just a user configuration issue, I'd love to iron this out -- either a troubleshooting guide so other users don't run into this, or changing the software to make it harder to misconfigure.

Just ran the test with you, running WinTAK 4.1.0 and taky 0.8.2, and was able to send packages back and forth.

**Comment by reldred** [comment]
Update: This issue can be resolved in most cases by removing all TAK Server connections, closing WinTAK and then navigating to %AppData%\WinTAK\SslCerts and emptying the folder out. Of particular note; TAKY server connection data packages always use the name 'server.p12', and WinTAK won't handle conflicting trust store cert names. Only connect to one Taky server at a time in WinTAK, basically.

**Comment by tkuester** [comment]
Oh man, that's a fascinating find! Do you think that's why the certificates were failing?

I don't think it would be too difficult to have the cert generation tool rename the .p12 file as something more specific to avoid conflicts!
