### ISSUE TITLE
Allow monitor port to see "private" messages

### ISSUE THREAD

**Issue by tkuester** [tkuester/taky#62]
Currently, the "monitor" port does not truly function as a monitor port. The monitor port should receive all communications, even if they are intended to be directly sent to a user. Currently, it only receives broadcasts.

**Comment by reldred** [comment]
This pleases me greatly. With this and Node RED I think I could create some really interesting/unique setups.

**Comment by tkuester** [comment]
Fix committed in d0581d6, set for merge in 0.9
