### ISSUE TITLE
Feature request: Server enforced max TTL on (archive) COTs

### ISSUE THREAD

**Issue by skadakar** [tkuester/taky#65]
Users of a semi-public TAK solution for hobby people leave long living/permanent markers on the map unknowingly and every time they visit the server they get re-sent. 

Some solution to not let any marker live more than x amount of time without being seint again would be useful.

**Comment by skadakar** [comment]
Example of a event that turns sticky, even many hours or weeks after the stale timestamp has passed it will be sent to new clients upon connecting. 


```
<event version="2.0" uid="b11f951e-29f1-4179-8f9e-8f4b94a44a9a" type="a-u-G" how="h-g-i-g-o" time="2022-03-27T00:36:16.781Z" start="2022-03-27T00:36:16.781Z" stale="2023-03-27T00:36:16.781Z">
  <point lat="REDACTED" lon="REDACTED" hae="169.3" ce="9999999.0" le="9999999.0"/>
  <detail>
    <status readiness="true"/>
    <archive/>
    <contact callsign="Bl&#229;&amp;appelsin Link Up"/>
    <archive/>
    <usericon iconsetpath="f7f71666-8b28-4b57-9fbb-e38e61d33b79/Google/blu-blank.png"/>
    <remarks/>
    <precisionlocation altsrc="DTED0"/>
    <color argb="-1"/>
    <link uid="ANDROID-ba157882afa58fbd" production_time="2021-10-23T23:49:02.393Z" type="a-f-G-U-C" parent_callsign="REDACTED" relation="p-p"/>
  </detail>
</event>
```

**Comment by skadakar** [comment]
For anyone waiting for a workaround, this is easy to do in node-red. 
Might be a better place to start messing with COTs and keep taky as close to a dumb router as possible.

**Comment by tkuester** [comment]
Added in 87fac0a!
