### ISSUE TITLE
Invalid Certificate Issue from Pi x64 Bullseye on LineageOS 19.1 (Android 13) CivTAK official 4.7.0.3

### ISSUE THREAD

**Issue by jonrau1** [tkuester/taky#78]
Unsure if it is _**actually**_ because of the OS version, but seems the only logical step to me. This behavior is the same for quickstart and for the regular extended deployment. It is the same whether I use root (pi, in my case) or setup another user.

Some OS Info. Running of a RPI 3B+ for what that matters. Setup is on local LAN on 10.0.0.0/16 space - Taky server set to the local address of 10.0.0.191

```
pi@pi:~ $ uname -r
5.15.76-v8+
pi@pi:~ $ uname
Linux
pi@pi:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Following the quickstart instructions, I was able to get the certificate installed from 10.0.0.191:8000/JENNY.zip without any issue on a LineageOS 19.1 device (Android 13) running the official tak[.]gov 4.7.0.3 image

```
pi@pi:~ $ python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
10.0.0.143 - - [17/Dec/2022 22:29:09] "GET /JENNY.zip HTTP/1.1" 200 -
```

I am given a variety of errors, first invalid certificate and when I look into the ATAK server configuration I am prompted for a username and password. Is there supposed to be one?

Next time I try it I am told to check the truststore - that is an ATAK error as well - unsure of what to do with that.

Any suggestions on how to troubleshoot this?

**Comment by tkuester** [comment]
Hey, I have just pushed out the 0.9 release of taky, which has completely overhauled the certificate generation routine. Please let me know if this works for you!

**Comment by tkuester** [comment]
@jonrau1 Any news on how things are going? If you aren't having any more issues, I'll close this.

**Comment by tkuester** [comment]
Closing this -- no more info! Please feel free to re-open if needed!
