### ISSUE TITLE
Route COTs on UID and Callsign

### ISSUE THREAD

**Issue by skadakar** [tkuester/taky#80]
There seems to be differences between TAK clients if they utilize `UID` or `Callsign` when trying to send info to other users, therefore Taky will need accept both inputs for routing COTs.

Issue discovered as Itak uses `UID`, where ATAK and Wintak use `Callsign` from my testing

**Comment by skadakar** [comment]
I believe this would also solve https://github.com/tkuester/taky/issues/70

**Comment by tkuester** [comment]
This was a fairly simple fix. I've got some test cases up, and code committed. Would love if anyone could do a quick test from the `routing-marti-uid` branch!

**Comment by skadakar** [comment]
Confirmed working with sending markers from itak to wintak.

**Comment by skadakar** [comment]
DP to multiple users including itak works, given that the package contains supported items for itak (so in this case 5markers in one package)
COT to single user in itak works
COT to multiple users in itak work
COT to broadcast in itak work

As far as my test goes everything works as expected.
