### ISSUE TITLE
error while using takyctl setup

### ISSUE THREAD

**Issue by YD1RUH** [tkuester/taky#93]
I've got error while run `takyctl setup ...`, after read the log, the error solved by change the code line **331** and **332** in file `/usr/local/lib/python3.8/dist-packages/taky/util/anc.py` with:

1. `"issued": cert.not_valid_before` to `"issued": cert.not_valid_before_utc` line **331**
2. `"expires": cert.not_valid_after` to `"expires": cert.not_valid_after_utc` line **332**

system information: **ubuntu 22.04**
hope this will help anyone that want to easy install **taky**.
73 de YD1RUH

**Comment by tkuester** [comment]
Thank you for your help, and thanks to @hunterSG7 for the fix!

As it so happens, `not_valid_before` has been deprecated in my cryptography library, and has been updated to `not_valid_after`. I'm going to take the time to implement this in the next branch, bump the dependency requirement, and take the opportunity to make sure I don't break anything else between versions!

**Comment by YD1RUH** [comment]
you're welcome my friend.. 😄
