### ISSUE TITLE
Reporting security issues

### ISSUE THREAD

**Issue by CyberXZT** [tkuester/taky#97]
Hi,

The project does not have any `SECURITY.md` and you do not have an email published. Do you have a way to privately submit security issues?

**Comment by tkuester** [comment]
Thanks for the suggestion! Implemented!

**Comment by CyberXZT** [comment]
@tkuester What is your discord? I don't actually see it anywhere.

**Comment by CyberXZT** [comment]
@tkuester Tracked you down and sent you a ping on discord.
